Repository kubernetes/org, pull requests merged in 2018-12, with the labels that each got.

#282 Add members 2018-11-30
  config/kubernetes-client/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#293 Include teams.yaml in bazel srcs
  WORKSPACE
  config/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#296 Add members 2018-12-10
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#305 Add piosz, brancz, dashpole to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#307 Add Monkeyanator to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#319 Add members 2018-12-19
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#320 Remove WIP note in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#325 Add members 2018-12-24
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#326 Add members 2018-12-26
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS
