Repository kubernetes/org, pull requests merged in 2018-10, with the labels that each got.

#130 Add new memberships - October 2
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#131 Add bertinatto to kubernetes, kubernetes-sigs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#135 Add members - October 2
  OWNERS_ALIASES
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 Add some members
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#140 Add justaugustus and mrbobbytables as front line membership reviewers
  config/kubernetes-client/OWNERS
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/OWNERS
  config/kubernetes-csi/org.yaml
  config/kubernetes-incubator/OWNERS
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/OWNERS
  config/kubernetes-sigs/org.yaml
  config/kubernetes/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 Add chaosaffe to k, k-sigs orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#143 Add m00nf1sh to k, k-sigs orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#144 Add flaper87 to the kubernetes-sig org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 Add liyinan926 to Kubernetes Org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Add Lion-Wei and m1093782566 to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#152 Add chrisohaver to Kubernetes Org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 Use area/github-* labels in issue templates
  .github/ISSUE_TEMPLATE/integrations.md
  .github/ISSUE_TEMPLATE/membership.md
  .github/ISSUE_TEMPLATE/repo-archive.md
  .github/ISSUE_TEMPLATE/repo-create.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#156 Add warmchang to kubernetes and kubernetes-incubator orgs
  config/kubernetes-incubator/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 Add dstrebel + pohly
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#161 Add alvaroaleman to k, k-sigs orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#166 Add gyuho + tizhou86
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#167 Add chentao1596 to Kubernetes Org
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#171 Add jinzhejz and mcrute to Kubernetes and Kubernetes-sigs Orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#176 Add new memberships - October 18th
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 Update the repo-create template with more questions
  .github/ISSUE_TEMPLATE/repo-create.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#177 Add marquiz to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#183 Add jingxu97 to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#185 Add new members (181023)
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#187 Add more kube-batch contributors to k-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#192 Add members to kubernetes / kubernetes-sigs orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 Add liggitt to k-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Add new org members - Oct 26
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#207 Add members to kubernetes and kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS
