Repository kubernetes/org, pull requests merged in 2018-11, with the labels that each got.

#212 Add new members (181030)
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#215 Add yue9944882 to kubernetes-incubator org
  config/kubernetes-incubator/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#220 New memberships - Nov 3
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#224 Add immutableT and idealhack to orgs.
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#226 Add animeshsingh and jbartosik to orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#228 Add wenjiaswe to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#234 Add members 09-11-2018
  config/kubernetes-client/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#241 Add aoxn and zhangqx2010 to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#247 Add fleeto and cofyc to orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#249 Add danielqsj to kubernetes, kubernetes-sigs orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#253 Add members 19112018
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#259 Add new members for Nov 20
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#263 Add yastij and jonpusifer to orgs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#265 New Members (181122)
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Add balajismaniam to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#271 Add hhoover to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#273 Add soggiest to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#278 Add users 2018-11-29
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS
