Repository kubernetes/org, pull requests merged in 2018-08, with the labels that each got.

#3 Add issue templates
  .github/ISSUE_TEMPLATE/general-support.md
  .github/ISSUE_TEMPLATE/integrations.md
  .github/ISSUE_TEMPLATE/membership.md
  .github/ISSUE_TEMPLATE/repo-archive.md
  .github/ISSUE_TEMPLATE/repo-create.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#11 ISSUE_TEMPLATE/membership: fix markdown rendering
  .github/ISSUE_TEMPLATE/membership.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Add some bazel and hack rules
  .bazelrc
  .kazelcfg.json
  BUILD.bazel
  WORKSPACE
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/update-all.sh
  hack/update-bazel.sh
  hack/update-deps.sh
  hack/update-gofmt.sh
  hack/verify-all.sh
  hack/verify-bazel.sh
  hack/verify-deps.sh
  hack/verify-gofmt.sh
  hack/verify_boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8 Script to apply declared config
  admin/BUILD.bazel
  admin/README.md
  admin/update.sh
  cmd/merge/BUILD.bazel
  cmd/merge/main.go
  config/BUILD.bazel
  config/config_test.go
  config/kubernetes-client/OWNERS
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/OWNERS
  config/kubernetes-csi/org.yaml
  config/kubernetes-incubator/OWNERS
  config/kubernetes-incubator/org.yaml
  config/kubernetes-retired/OWNERS
  config/kubernetes-retired/org.yaml
  config/kubernetes-sigs/OWNERS
  config/kubernetes-sigs/org.yaml
  config/kubernetes/OWNERS
  config/kubernetes/org.yaml
  config/kubernetes/sig-contributor-experience/OWNERS
  config/kubernetes/sig-contributor-experience/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 Update from dump - Aug 30
  config/kubernetes-client/org.yaml
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
