Repository kubernetes/org, pull requests merged in 2019-03, with the labels that each got.

#548 Add members 2019-02-28
  config/kubernetes-csi/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#554 Add rjbez17 to kubernetes org.
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#552 Add rjbez17 to conformance wg members
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#555 Add members 2019-03-01
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#556 Add members 2019-03-03
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#538 Rename PST team to PSC
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#560 Add sboeuf and rhatdan to cri-o-maintainers team
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#562 Setup teams and org membership for k8s-container-image-promoter
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#561 Add members 2019-03-04
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#546 Add sig docs it teams and update fr teams
  .gitignore
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/M

#565 Add soggiest to milestone-maintainers team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#568 Add teams for Azure CSI repo migrations
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-azure/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/S

#569 Add dlipovetsky to etcdadm teams
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#558 Add publishing-bot-reviewers team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#570 add ncdc to cluster-api-maintaners and cluster-api-provider-aws-maintainers
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#572 Add brad as resizer repo admin
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#575 Add members 2019-03-06
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#578 Add xmudrii to kubernetes-milestone-maintainers
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#580 Add randomvariable to cluster-api-provider-aws-maintainers
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#566 Migrate team maintainers to members
  config/config_test.go
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
  config/kubernetes-sigs/sig-azure/teams.yaml
  config/kubernetes/org.yaml
  config/kubernetes/sig-api-machinery/teams.yaml
  config/kubernetes/sig-apps/teams.yaml
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-auth/teams.yaml
  config/kubernetes/sig-autoscaling/teams.yaml
  config/kubernetes/sig-aws/teams.yaml
  config/kubernetes/sig-azure/teams.yaml
  config/kubernetes/sig-big-data/teams.yaml
  config/kubernetes/sig-cli/teams.yaml
  config/kubernetes/sig-cloud-provider/teams.yaml
  config/kubernetes/sig-cluster-lifecycle/teams.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-docs/teams.yaml
  config/kubernetes/sig-gcp/teams.yaml
  config/kubernetes/sig-instrumentation/teams.yaml
  config/kubernetes/sig-multicluster/teams.yaml
  config/kubernetes/sig-network/teams.yaml
  config/kubernetes/sig-openstack/teams.yaml
  config/kubernetes/sig-pm/teams.yaml
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-scalability/teams.yaml
  config/kubernetes/sig-scheduling/teams.yaml
  config/kubernetes/sig-service-catalog/teams.yaml
  config/kubernetes/sig-storage/teams.yaml
  config/kubernetes/sig-windows/teams.yaml
  config/kubernetes/wg-component-standard/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, sig/apps, sig/architecture, sig/auth, sig/autoscaling, sig/aws, sig/azure, sig/big-data, sig/cli, sig/cloud-provider, sig/cluster-lifecycle, sig/contributor-experience, sig/docs, sig/gcp, sig/instrumentation, sig/multicluster, sig/network, sig/openstack, sig/pm, sig/release, sig/scalability, sig/scheduling, sig/service-catalog, sig/storage, sig/windows, size/XXL, wg/component-standard

#582 Add members 2019-03-07
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#576 Add teams for k-sigs/multi-tenancy
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-auth/OWNERS
  config/kubernetes-sigs/sig-auth/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#586 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#585 Add krmayankk to kubernetes-milestone-maintainers team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#591 Revert migrate maintainers to members for kubernetes-incubator
  config/config_test.go
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#577 Add umohnani8 to cri-o maintainers team
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#593 Add members 2019-03-11
  config/kubernetes-client/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#598 Add dummy team for testing prow project plugin
  config/kubernetes/sig-testing/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#597 Clean up group membership for roberthbailey
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
  config/kubernetes/sig-cluster-lifecycle/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/release, size/S

#600 Add members 2019-03-13
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#601 Update teams for sig-azure
  config/kubernetes-sigs/sig-azure/teams.yaml
  config/kubernetes/sig-azure/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/S

#607 Add members 2019-03-14
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#604 Add wg-lts leads owner alias and wg-lts team
  OWNERS_ALIASES
  config/kubernetes/wg-lts/OWNERS
  config/kubernetes/wg-lts/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#606 Add tashimi to multi-tenancy sub-project teams
  config/kubernetes-sigs/sig-auth/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/auth, size/XS

#602 Remove owners team in kubernetes-incubator org
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#617 sig-pm: Update teams
  config/kubernetes/sig-pm/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/XS

#610 Add srampal to multi-tenancy teams
  config/kubernetes-sigs/sig-auth/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/auth, size/XS

#616 Add new members (3/16/19)
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#618 Add client go teams
  config/kubernetes-client/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#620 Add members 2019-03-17
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#625 Add members 2019-03-18
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#624 Add community-milestone-maintainers team
  config/kubernetes/sig-contributor-experience/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/S

#629 Add teams for kubernetes-client/perl
  config/kubernetes-client/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#631 Add teams for addon-operators
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-cluster-lifecycle/OWNERS
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#633 Add hex108 to kubernetes-sigs members
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 Grant SCL leads admin access to all SCL subproject repos
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#636 add neolit123 to kubernetes-milestone-maintainers
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#638 Update OWNERS and SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#639 Add members 2019-03-20
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#645 Add members 2019-03-22
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#644 Add milestone team for SIG Docs
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/L

#650 team add: kubernetes-patch-release-team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#646 Add saschagrunert to cri-o-maintainers team
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#652 Add members 2019-03-25
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#647 Add German language team members
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/docs, size/S

#653 Don't ask approvers and security contacts for staging repos
  .github/ISSUE_TEMPLATE/repo-create.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#654 adding jimangel to kubernetes-incubator
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#649 Add tengqm to reference-docs maintainers.
  config/kubernetes-incubator/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, priority/important-soon, sig/docs, size/XS, tide/squash

#656 Updated descriptions for sig-docs-[de|en]-owners
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#661 Add members 2019-03-27
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#657 Add adisky to cloud provider OpenStack Maintainers
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#659 Remove chenopis, add jaredbhatti
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#664 patch-release-team: re-add @foxish for 1.11.10
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#666 Add slack-infra-admins team
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-contributor-experience/OWNERS
  config/kubernetes-sigs/sig-contributor-experience/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#665 Add bburns to openapi perl admin/write
  config/kubernetes-client/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#668 Add teams for cli-experimental
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-cli/OWNERS
  config/kubernetes-sigs/sig-cli/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#669 Add folks to cluster-api-vsphere
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
