Repository kubernetes/org, pull requests merged in 2019-02, with the labels that each got.

#446 Add members 2019-02-04
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#452 Update group membership for roberthbailey.
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#454 Add members 2019-02-06
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#445 Add code-of-conduct-committee team
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, committee/conduct, lgtm, size/XS

#458 Add Katharine to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#460 Add vincepri to cluster-api-maintainers
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#463 Add members 2019-02-08
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm

#466 Add members 2019-02-11
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#469 Add teams for kubernetes-sigs/windows-gmsa access
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-windows/OWNERS
  config/kubernetes-sigs/sig-windows/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#390 Add csi-misc team to tag all developers
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#473 Add members 2019-02-12
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#459 Add vincepri to cluster-api-provider-aws-maintaners
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#474 Correct jichenjc membership
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#442 Add myself to k8s.io/kops
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#481 Add members 2019-02-13
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#491 Update Azure teams + add ritazh to k,k-sigs
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
  config/kubernetes/sig-azure/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/XS

#489 Add members 2019-02-14
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#493 Add dims as maintainer for k/k8s.io repo
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#497 Add members 2019-02-16
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#502 Add members 2019-02-18
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#496 sig-pm: Add project-board-maintainers team
  config/kubernetes/sig-pm/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/XS

#505 Add teams for kubernetes-sigs/kubebuilder-declarative-pattern
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-api-machinery/OWNERS
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#507 Add members 2019-02-19
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#506 Move structured-merge-diff and yaml teams to api-machinery dir
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/M

#512 Add k8s-github-robot alongside k8s-ci-robot in all orgs
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-incubator/org.yaml
  config/kubernetes-retired/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#514 Add members 2019-02-20
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#517 Add teams for kubernetes-csi/csi-driver-image-populator
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#498 sig-pm: Update `enhancements-maintainers` team
  config/kubernetes/sig-pm/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/M

#521 Add team for kubernetes-csi.github.io
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#523 sig-release: Update kubernetes-milestone-maintainers description
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#524 Add members 2019-02-23
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#526 Add 1.14 CI Signal team as milestone maintainers
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#533 One-character typo fix
  .github/ISSUE_TEMPLATE/general-support.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#534 Add teams for French localization
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#536 Sync up team members for apiserver-builder-alpha
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#539 Add members 2019-02-27
  config/kubernetes-incubator/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#541 add adohe to kubernetes-incubator
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#522 prune sig-testing teams
  config/kubernetes/sig-testing/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M

#544 add admins for cloud-provider-alibaba repo
  config/kubernetes/sig-cloud-provider/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cloud-provider, size/XS

#545 Add smourapina (CI Signal 1.14) as milestone maintainer
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
