Repository kubernetes/org, pull requests merged in 2019-05, with the labels that each got.

#780 Add admins-cluster-proportional-vertical-autoscaler team
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#781 Add members 2019-05-01
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#784 Add teams for cluster-api-provider-ibmcloud
  config/kubernetes-sigs/sig-ibmcloud/OWNERS
  config/kubernetes-sigs/sig-ibmcloud/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#785 Added more maintainers for cluster api ibm cloud
  config/kubernetes-sigs/sig-ibmcloud/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#788 Add members 2019-05-03
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#790 sig-docs: fix description for admin teams
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#791 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#792 Add alenkacz to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#793 Remove XiaoningDing from kubernetes
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#796 Add members 2019-05-06
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#783 Added mkorbi to German translation team
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#800 add andyxning to sig-instrumentation
  config/kubernetes/sig-instrumentation/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/instrumentation, size/XS

#802 Add teams for cli-utils
  config/kubernetes-sigs/sig-cli/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cli, size/S

#803 add members 2019-05-08
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#797 Remove some unneeded teams
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#804 Add kubernetes-feature-branch-admins group
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 Add members 2019-05-10
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#808 Add teams for release-notes
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-release/OWNERS
  config/kubernetes-sigs/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#748 Add sig-docs-hi members
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/docs, size/S

#810 Update product-security-committee
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#813 Add netlify site request issue template.
  .github/ISSUE_TEMPLATE/site-create.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#814 Fix up docs groups
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#815 Add k8s-release-robot to milestone-maintainers team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#817 Add MAKOSCAFEE to website-milestone-maintainers
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS, tide/merge-method-squash

#819 Rename federation-v2 to kubefed
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-multicluster/OWNERS
  config/kubernetes-sigs/sig-multicluster/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#820 Add members 2019-05-14
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#825 added 1.15 branch managers to k-release-managers
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#827 Add members 2019-05-16
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#829 Update SIG PM teams
  config/kubernetes/sig-pm/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/S

#821 Add juandiegopalomino to website-milestone-maintainers
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/docs, size/XS

#834 Add members 2019-05-20
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#840 Add members 2019-05-23
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#843 Add members 2019-05-26
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#847 Add membership to irvifa in kubernetes-client.
  config/kubernetes-client/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#852 Add myself to @kubernetes-csi
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#849 Enforce non-admins shouldn't be team maintainers
  config/config_test.go
  config/kubernetes-incubator/org.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#856 Remove nesting from release manager teams
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#857 Fix description for stage-bots team
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#858 Add new members (5/30/19)
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#859 Add team for youtube-admins
  config/kubernetes/sig-contributor-experience/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/S

#828 Update SIG Release teams
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#853 Cleaning description of the teams
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/XL

#866 add jberkhahn to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#867 Add members 2019-05-30
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#865 Update service catalog teams
  config/kubernetes-sigs/sig-service-catalog/OWNERS
  config/kubernetes-sigs/sig-service-catalog/teams.yaml
  config/kubernetes/sig-service-catalog/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/service-catalog, size/M

#868 add MHBauer
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#869 add jeffvance to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
