Repository kubernetes/org, pull requests merged in 2020-12, with the labels that each got.

#2351 Add GitHub team for kubectl-check-ownerreferences
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#2360 Add bentheelder to Kubernetes maintainers team.
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2361 Add Members 12-03-2020
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2366 Add members 12-04-2020
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2364 Add annajung to website-maintainers team for 1.20 release
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/docs, size/XS

#2368 Add tallclair to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2357 Refine too many args for fmt string
  cmd/merge/main.go
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2372 k-csi: remove GitHub teams for fibre-channel and flex repos
  config/kubernetes-csi/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/M

#2346 Add alvaroaleman to controller-runtime maintainers
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#2375 Add Pensu to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2367 Add ArangoGutierrez to NFD_operator maintainers
  config/kubernetes-sigs/sig-node/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, ok-to-test, sig/node, size/XS

#2380 cluster-api: ncdc stepping down from maintainership
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#2384 Add Members 12-14-2020
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2385 Add habibrosyad to sig-docs-id-reviews
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/docs, size/XS

#2377 Remove 1.20 shadows from sig docs teams
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/docs, size/XS

#2393 Add Members 12-18-2020
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2394 Add coderanger to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, area/github-membership, cncf-cla: yes, lgtm, size/XS
