Repository kubernetes/org, pull requests merged in 2020-03, with the labels that each got.

#1682 Add members 2019-03-03
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1684 Add craiglpeters to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1685 Add cpanato to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1687 add coffeepac to several of the sig-inst lists
  config/kubernetes/sig-instrumentation/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/instrumentation, size/XS

#1686 Update SIG Instrumentation leads
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1683 add kbhawkey to sig-docs
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1697 Add rajansandeep to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1704 Add members 2020-03-11
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1705 Add GitHub teams for cloud-provider-huaweicloud
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cloud-provider, size/S

#1706 Add GitHub teams for iptables-wrappers
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/S

#1708 Add benmoss to sig-windows-tools-admins
  config/kubernetes-sigs/sig-windows/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS

#1715 Remove nicoaragon from kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1718 Add members 2020-03-16
  config/kubernetes-client/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1717 Add serathius as milestone maintainer for sig instrumentation
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1721 Remove write access to cluster-api-do repo for nikhita
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#1720 Add gnarled-cipher to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1722 Remove alvaroaleman fro cluster-api-provider-digitalocean-maintainers
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#1723 Add teams for the kubernetes-client/c repo
  config/kubernetes-client/org.yaml
Labels: approved, area/github-repo, cncf-cla: yes, lgtm, size/S

#1728 Add prksu to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1601 Add team members to application-admins
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1727 Add marosset and remove patricklang as milestone maintainers for sig windows
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1733 Add GitHub teams for clientgofix
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#1735 Add MorrisLaw to kubernetes-sigs org.
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1737 Adding marosset to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1681 Add hectorj2f to kubefed maintainers
  config/kubernetes-sigs/sig-multicluster/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#1741 Add members 2020-03-24
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1745 Add teams for cloud-provider-baiducloud repo
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Labels: approved, area/github-repo, cncf-cla: yes, lgtm, sig/cloud-provider, size/S

#1748 Remove myself from teams I don't participate in
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
  config/kubernetes-sigs/sig-multicluster/teams.yaml
  config/kubernetes/org.yaml
  config/kubernetes/sig-scalability/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/multicluster, sig/scalability, size/S

#1750 Add GitHub teams for sig-storage repos
  config/kubernetes-sigs/sig-storage/OWNERS
  config/kubernetes-sigs/sig-storage/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1762 Add members 2020-03-29
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1761 Add GitHub teams for kubebuilder-release-tools
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#1758 Add new cluster-api-provider-digitalocean maintainers
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS
