Repository kubernetes/org, pull requests merged in 2020-04, with the labels that each got.

#1747 Update SIG Docs tech leads
  OWNERS_ALIASES
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#1738 Update Italian localization teams & corrected language affilation
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#1766 Add humblec to kubernetes-csi org
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1767 Add GitHub teams for wg-policy-prototypes
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/wg-policy/OWNERS
  config/kubernetes-sigs/wg-policy/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1768 Add gnufied as external-resizer maintainer
  config/kubernetes-csi/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1769 Add members 2020-04-03
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1771 Add @sftim as website maintainer
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#1772 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/M

#1159 Add yue to kubernetes java client admin
  config/kubernetes-client/org.yaml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, sig/contributor-experience, size/XS

#1770 Add member to sig-docs-ko-approver
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#1776 Add loburm to Kubernetes SIGs group.
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1754 add wahyuoi to sig-docs-id-reviews
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#1775 sig-contribex: add castrojo to OWNERS_ALIASES and teams
  OWNERS_ALIASES
  config/kubernetes/sig-contributor-experience/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/XS

#1779 Add x13n to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1781 Remove apelisse from dep approvers
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1782 Add members 2020-04-09
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1785 Update SIG Release teams
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#1786 Added alejandrox1 as milestone maintainer for SIG testing
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1788 Add teams for kubernetes-sigs/boskos
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-testing/OWNERS
  config/kubernetes-sigs/sig-testing/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1789 Add members 2020-04-14
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1794 Add hectorj2f to kubefed-admins team
  config/kubernetes-sigs/sig-multicluster/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#1796 sig-pm: Retire/delete/transfer SIG's GitHub teams
  OWNERS_ALIASES
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-pm/OWNERS
  config/kubernetes/sig-pm/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/architecture, sig/contributor-experience, sig/pm, size/L

#1802 Add GitHub teams for gluster provisioner repos
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-storage/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/storage, size/S

#1799 sig-arch: Consolidate GitHub teams
  config/kubernetes/sig-architecture/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/architecture, size/M

#1807 Add members 2019-04-20
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS

#1805 steering: switch timothysc for lachie83
  OWNERS_ALIASES
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1813 Remove GitHub teams for kubernetes-anywhere repo
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1815 Update SIG Docs team membership
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#1822 Add team for GHAS folks to be able to edit project board
  config/kubernetes/sig-contributor-experience/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/S

#1824 Migrate teams for kubernetes-incubator/cluster-proportional* repos
  config/kubernetes-incubator/org.yaml
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/M

#1827 Remove danielromlein from org
  config/kubernetes/org.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1828 Remove pbx0 from kubernetes-incubator
  config/kubernetes-incubator/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1836 Add members 2020-04-23
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/S

#1839 Add 1.19 release CI Signal team members
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1842 Add members 2019-04-29
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS
