Repository kubernetes/org, pull requests merged in 2020-06, with the labels that each got.

#1910 Add GitHub teams for instrumentation-tools
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-instrumentation/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/instrumentation, size/S

#1911 Add karan to sig-node-test-failures
  config/kubernetes/sig-node/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/node, size/XS

#1914 Add members 2020-06-02
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1917 Add members 2020-06-04
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1918 add cloud-provider-aws admin/maintainers teams for k8s.io/cloud-provider-aws
  config/kubernetes/sig-cloud-provider/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cloud-provider, size/S

#1919 sig-release: Cleanup teams
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#1920 update sig testing
  OWNERS_ALIASES
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1909 Add kbruner as milestone maintainer
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1922 CAPZ: add reviewers to cluster-api-provider-azure-pms
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#1923 Add members 2020-06-11
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1925 Add Release Manager Associates to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1924 sig-release: Add a release-engineering team to kubernetes-sigs
  config/kubernetes-sigs/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#1928 Add roycaihw to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1931 Add reviewers and owners for website Ukrainian localization
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#1933 Add members 2020-06-15
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1932 config/kubernetes/org.yaml: update kubeadm-maintainers
  config/kubernetes/org.yaml
  config/kubernetes/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, sig/cluster-lifecycle, size/M

#1937 Add chizhg to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1940 Update slack channel and mailing list in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1941 Add alonyb to kubernetes org
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1943 Add yodahekinsew to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1944 sig-release: Add active image promoter contribs to release-engineering
  config/kubernetes-sigs/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#1945 update 'provider-openstack' admin list
  config/kubernetes/sig-openstack/teams.yaml
Labels: approved, area/provider/openstack, cncf-cla: yes, lgtm, sig/cloud-provider, size/S

#1948 Add members 2020-06-24
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1950 Add gianarb to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1952 Add gnufied to ebs CSI driver
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-aws/teams.yaml
Labels: approved, area/provider/aws, cncf-cla: yes, lgtm, sig/cloud-provider, size/XS

#1954 Remove stale invites
  config/kubernetes/org.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, sig/testing, size/XS

#1956 Add GitHub teams for COSI repos
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-storage/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/storage, size/M

#1958 Add members 2020-06-25
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1935 Add cluster-api-provider-packet-admins and maintainers teams
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/cloud-provider, sig/cluster-lifecycle, size/S

#1961 Add members 2020-06-26
  config/kubernetes/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1962 Add knight42 to the kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1963 Add yuanchen8911 to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1968 Add members 2020-06-30
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-membership, cncf-cla: yes, lgtm, size/XS
