Repository kubernetes/org, pull requests merged in 2021-02, with the labels that each got.

#2477 Add GitHub team for work-api repo
  config/kubernetes-sigs/sig-multicluster/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#2479 Add members 2021-02-02
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2484 Add members 2021-02-08
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2491 Renaming Service APIs to Gateway API
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/network, size/S

#2497 SIG Instrumentation members cleanup
  config/kubernetes/sig-instrumentation/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/instrumentation, size/L

#2499 Add Members 02-11-2021
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2502 Offboard Craig
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2419 kubernetes-sigs/sig-api-machinery: add estroz to kubebuilder-admins
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/XS

#2503 Add members 2021-02-16
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2504 Remove dankohn from Kubernetes org
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2509 cluster-api-provider-digitalocean: Update team membership
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#2510 Add divya-mohan0209 to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2513 Add members 2021-02-19
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2139 added yliaog to gen/go/go-base/java team
  config/kubernetes-client/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2518 Add GitHub teams for hierarchical-namespaces
  config/kubernetes-sigs/sig-auth/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/auth, size/S

#2524 Edit description for milestone-maintainers to reflect triage access
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/XS

#2526 add members to k8s-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2523 updating Korean website milestone maintainers
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/docs, size/XS

#2529 Remove GitHub teams for mutating-trace-admission-controller
  config/kubernetes-sigs/sig-instrumentation/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/instrumentation, size/S

#2530 Add members 2021-02-26
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2521 Add rficcaglia to wg-policy-prototypes members
  config/kubernetes-sigs/wg-policy/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, ok-to-test, size/XS, wg/policy
