Repository kubernetes/org, pull requests merged in 2021-05, with the labels that each got.

#2686 Add gcp-compute-persistent-disk-csi-driver groups
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/S

#2690 Add Members 2021-05-06
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2694 Add PRR team to GitHub teams
  config/kubernetes/sig-architecture/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/architecture, size/S

#2693 Add Jiawei0227 to some kubernetes-csi repo maintainer
  config/kubernetes-csi/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2696 Add GitHub team for provider-aws-test-infra
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/cloud-provider, size/XS

#2697 Add GitHub teams for network-policy-api
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/network, size/XS

#2698 Add yangjunmyfm192085 to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2706 Add myself to members list
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2707 Add Members 2021-05-12
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2708 Add kbasv to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2709 Add astoycos to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2711 Add GitHub teams for cosi-driver-sample
  config/kubernetes-sigs/sig-storage/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/storage, size/S

#2710 Add thejoycekung and verolop to release-team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/XS

#2714 Add coffeepac and monotek to k8s-sigs
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2700 Add eddiezane to kubectl-admins and prune
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/S

#2720 Add missing 1.22 RT members to RT group and milestone maintainers list
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, priority/critical-urgent, sig/release, size/XS

#2722 Adding `vladimirvivien` as admin to e2e-framework repo
  config/kubernetes-sigs/sig-testing/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/testing, size/XS

#2723 Add KnVerey to milestone members
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/XS

#2724 Add members 2021-05-23
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2695 Add seanmalloy to external-dns-maintainers
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, ok-to-test, sig/network, size/XS

#2727 Add seanschneeweiss to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2728 Add yangjunmyfm192085 to sig-instrumentation team
  config/kubernetes/sig-instrumentation/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/instrumentation, size/XS

#2731 Add wg structured logging teams
  OWNERS_ALIASES
  config/kubernetes/wg-structured-logging/OWNERS
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/S

#2726 Add prameshj and swetharepakula into ingress-gce maintainer
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2734 Add members 2021-05-26
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2733 add kikisdeliveryservice as enhancements subproject owner
  config/kubernetes/sig-architecture/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/architecture, size/S

#2738 Adding yangjunmyfm192085 to wg structured logging
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2730 Update metrics server admins.
  config/kubernetes-sigs/sig-instrumentation/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/instrumentation, size/XS

#2739 add Priyankasaggu11929 to wg-structured-logging
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2741 wg-k8s-infra: add more sub-teams
  config/kubernetes/wg-k8s-infra/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/M, wg/k8s-infra

#2742 Add Members 2021-05-28
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2744 Add WG stuctured logging leads to members and reviewers
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS, wg/structured-logging

#2746 Update username rename: s/GreenApple10/chuntaochen
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2743 releng: Update `release-engineering` team
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-release/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/S

#2748 Add MadhavJivrajani to structured logging members list
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2749 Add navidshaikh to wg structured logging
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2750 Add yuzhiquan to wg structured logging
  config/kubernetes/wg-structured-logging/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS
