Repository kubernetes/org, pull requests merged in 2021-06, with the labels that each got.

#2753 Add myself as ingress-nginx admin
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2758 Add members 2021-06-03
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2757 Add GitHub team for sig-windows-dev-tools
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-windows/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/windows, size/S

#2764 Add members 2021-06-04
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2747 SIG Release: Spring cleaning
  config/kubernetes-sigs/sig-release/teams.yaml
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, sig/testing, size/M

#2769 Update kustomize teams to match in-repo lists.
  config/kubernetes-sigs/sig-cli/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/cli, size/XS

#2759 add self as maintainer for aws-ebs-csi-driver
  config/kubernetes-sigs/sig-aws/teams.yaml
Labels: approved, area/github-management, area/provider/aws, cncf-cla: yes, lgtm, ok-to-test, sig/cloud-provider, size/XS

#2767 Replace inactive owners
  OWNERS_ALIASES
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2772 add pacoxu to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2773 Remove cosi-driver-minio GitHub teams
  config/kubernetes-sigs/sig-storage/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/storage, size/S

#2765 Add self as admin for efs and fsx and remove inactive
  config/kubernetes-sigs/sig-aws/teams.yaml
Labels: approved, area/github-management, area/provider/aws, cncf-cla: yes, lgtm, sig/cloud-provider, size/XS

#2777 Update GitHub username for medmedchiheb
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2780 Update 1.22 Comms team
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, priority/critical-urgent, sig/release, size/XS

#2787 Add Members 06-14-2021
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2781 jeefy stepping down from sig-ui chair
  OWNERS_ALIASES
  config/kubernetes/org.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/XS

#2782 sig-release: add puerco/cpanato to the sig-release teams
  OWNERS_ALIASES
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/S

#2784 config: Add tylerferrara to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2797 updating teams
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/docs, size/S

#2791 Add shu-mutou to sig-ui leads
  OWNERS_ALIASES
  config/kubernetes/sig-release/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/release, size/XS

#2802 Add members 20210622
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, area/github-membership, cncf-cla: yes, lgtm, size/XS

#2762 Update admins for cloud-provider-vsphere
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2805 Add members 2021-06-25
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2807 Add 249043822 to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2810 Add members 2021-06-30
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, size/XS

#2811 Add jpbetz to structured-merge-diff-maintainers
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: approved, area/github-management, cncf-cla: yes, lgtm, sig/api-machinery, size/XS
