Repository kubernetes/org, pull requests merged in 2022-10, with the labels that each got.

#3737 Add atoato88 as sig-docs-ja-reviews
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#3744 Rename kris-nova to krisnova
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3745 Add Members 2022-10-03
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#3735 Create team for Release Notes
  config/kubernetes/sig-release/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#3746 Onboard/Offboard Steering Committee members as per 2023 elections
  OWNERS_ALIASES
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3748 drop googlers that no longer have deb/rpm access from build-admins
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#3751 Add haircommander to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3752 Add fromanirh to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3750 Add new maintainers to image-builder project
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3758 sig-network: Add ingress2gateway teams
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/network, area/github-repo, area/github-management

#3757 OWNERS_ALIASES: update sig-testing-leads
  OWNERS_ALIASES
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3763 Add members 2022-10-12
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#3767 Update CoCC membership for new members
  OWNERS_ALIASES
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3768 Add sig auth tools teams
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-auth/teams.yaml
Labels: sig/auth, size/S, approved, cncf-cla: yes, lgtm, area/github-repo, area/github-management

#3770 drop palnabarun from code-of-conduct-committee team
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3776 Remove ihmccreery, username does not exist anymore
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3778 Add rajaskakodkar to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3780 Add teams for tejolote repo
  config/kubernetes-sigs/sig-release/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#3784 Update username for alexander-demichev
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#3787 Update sig docs website-maintainers and website-milestone-maintainers
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#3786 Remove Josh since his departure from the maintaining org
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, ok-to-test, area/github-management
