Repository kubernetes/org, pull requests merged in 2022-04, with the labels that each got.

#3349 Add mauriciopoppe as maintainer and admin of local-static-provisioner
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3338 Add rohityadavcloud and davidjumani to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3359 Rotate fejta,spiffxp for ameukam,palnabarun in GitHub Admin Team
  Makefile
  OWNERS
  SECURITY_CONTACTS
  admin/update.sh
  config/kubernetes-client/OWNERS
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/OWNERS
  config/kubernetes-csi/org.yaml
  config/kubernetes-incubator/OWNERS
  config/kubernetes-incubator/org.yaml
  config/kubernetes-nightly/OWNERS
  config/kubernetes-nightly/org.yaml
  config/kubernetes-nightly/sig-release/teams.yaml
  config/kubernetes-retired/OWNERS
  config/kubernetes-retired/org.yaml
  config/kubernetes-sigs/OWNERS
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-contributor-experience/teams.yaml
  config/kubernetes-sigs/sig-k8s-infra/teams.yaml
  config/kubernetes-sigs/sig-release/teams.yaml
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/kubernetes/OWNERS
  config/kubernetes/org.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-k8s-infra/teams.yaml
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
Labels: size/L, sig/testing, approved, sig/contributor-experience, cncf-cla: yes, lgtm, sig/release, area/github-management, sig/k8s-infra

#3366 Add members 2022-04-10
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#3367 Remove inactive members
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
  config/kubernetes/sig-network/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#3358 Update admins/maintainers for k8s-sigs/cluster-api-provider-packet
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#3369 Retire poseidon teams
  config/kubernetes-sigs/sig-scheduling/teams.yaml
Labels: size/S, sig/scheduling, approved, cncf-cla: yes, lgtm, area/github-management

#3371 Remove inactive members
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3375 Add everpeace to kubernetes-sigs organization
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3370 Add teams for testgrid-json-exporter
  config/kubernetes-sigs/sig-release/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#3382 Remove Kashomon from github orgs
  config/kubernetes/org.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
Labels: size/XS, approved, sig/contributor-experience, cncf-cla: yes, lgtm, area/github-management

#3296 add self as maintainer for aws-ebs-csi-driver
  config/kubernetes-sigs/sig-aws/teams.yaml
Labels: size/XS, area/provider/aws, approved, sig/cloud-provider, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3354 Add ptux to sig-docs-ja-reviews
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#3395 Add apricote to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3391 add andyzhangx as maintainer & admin of local-static-provisioner
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3380 Add wzshiming to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3396 add kerthcet to kubernetes-sig org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management
