Repository kubernetes/org, pull requests merged in 2022-07, with the labels that each got.

#3534 Add arhell as member in kubernetes-csi
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3535 Add arhell as member in kubernetes-client
  config/kubernetes-client/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3540 Add members 2022-07-04
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#3552 add m-Bilal to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3531 Adding Shane Utt as Gateway API Maintainer
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#3556 releng: RMA Onboarding for Jeremy and Joseph
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm, sig/release, area/github-management

#3553 Add David Vossel as cluster-api-provider-kubevirt admin/maintainer
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3546 Add jprzychodzen to cloud-provider-gcp-maintainers
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3560 Add carolinar7 to kubernetes.
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, tide/merge-method-squash, area/github-membership, ok-to-test, area/github-management

#3563 Add members 2022-07-16
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#3576 add shaneutt to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3577 sig-node: add endocrimes to teams
  config/kubernetes/sig-node/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/node, area/github-management

#3573 Adding Gateway API Mesh Leads
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#3580 Add GitHub teams for kwok repo
  config/kubernetes-sigs/sig-scheduling/teams.yaml
Labels: size/S, sig/scheduling, approved, cncf-cla: yes, lgtm, area/github-management

#3579 add zqzten to kubernetes, kubernetes-sigs, kubernetes-client
  config/kubernetes-client/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3545 Add Prajyot-Parab to kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3547 kubernetes-csi: jingxu97 as admin of csi-driver-host-path
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3581 Add Members 2022-07-28
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3528 Adding new maintainers to CAPC repo
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, ok-to-test, area/github-management
