Repository kubernetes/org, pull requests merged in 2023-07, with the labels that each got.

#4320 update czybjtu to nayihz
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#4322 Add members 2023-07-07
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4274 Rotate SIG Testing chairs
  OWNERS_ALIASES
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
Labels: sig/testing, size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4323 Add noderesourcetopology-api teams
  config/kubernetes-sigs/sig-node/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/node, area/github-management

#4314 Housekeeping SIG Docs OWNERS_Aliases and teams.yaml
  OWNERS_ALIASES
  config/kubernetes/sig-docs/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/M, area/github-management

#4321 Offboard Luke Hinds from SRC
  OWNERS_ALIASES
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4310 add Dan Winship as an admin
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#4220 Update teams.yaml to address remaining changes for the v1.28 release cycle
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, sig/architecture, cncf-cla: yes, lgtm, sig/release, ok-to-test, area/github-management

#4331 Add members 2023-07-14
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4332 Add self to kubernetes-csi org
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4334 REQUEST: New kubernetes-csi membership for wackxu
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4335 Add jefftree to kube-openapi maintainers
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4340 Add members 2023 07 19
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#4341 add zhanggbj to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4344 Add willie-yao to kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#4346 Add ydFu to sig-docs-zh-owners
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#2614 Use peribolos to manage team repo permissions
  cmd/helpers/helper.go
  cmd/restrictions/main.go
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/provider-azure/teams.yaml
  config/kubernetes-sigs/provider-ibmcloud/teams.yaml
  config/kubernetes-sigs/provider-vmware/teams.yaml
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
  config/kubernetes-sigs/sig-apps/teams.yaml
  config/kubernetes-sigs/sig-architecture/teams.yaml
  config/kubernetes-sigs/sig-auth/teams.yaml
  config/kubernetes-sigs/sig-aws/teams.yaml
  config/kubernetes-sigs/sig-cli/teams.yaml
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
  config/kubernetes-sigs/sig-contributor-experience/teams.yaml
  config/kubernetes-sigs/sig-docs/teams.yaml
  config/kubernetes-sigs/sig-instrumentation/teams.yaml
  config/kubernetes-sigs/sig-k8s-infra/teams.yaml
  config/kubernetes-sigs/sig-multicluster/teams.yaml
  config/kubernetes-sigs/sig-network/teams.yaml
  config/kubernetes-sigs/sig-node/teams.yaml
  config/kubernetes-sigs/sig-release/teams.yaml
  config/kubernetes-sigs/sig-scheduling/teams.yaml
  config/kubernetes-sigs/sig-storage/teams.yaml
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/kubernetes-sigs/sig-windows/teams.yaml
  config/kubernetes-sigs/wg-component-standard/teams.yaml
  config/kubernetes-sigs/wg-policy/teams.yaml
  config/kubernetes/org.yaml
  config/kubernetes/provider-openstack/teams.yaml
  config/kubernetes/sig-apps/teams.yaml
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-cli/teams.yaml
  config/kubernetes/sig-cloud-provider/teams.yaml
  config/kubernetes/sig-cluster-lifecycle/teams.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-docs/teams.yaml
  config/kubernetes/sig-instrumentation/teams.yaml
  config/kubernetes/sig-k8s-infra/teams.yaml
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-scalability/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
  config/restrictions.yaml
  go.mod
  go.sum
  hack/verify-restrictions.sh
Labels: sig/auth, area/provider/aws, sig/multicluster, sig/testing, area/provider/vmware, sig/storage, area/provider/ibmcloud, sig/scheduling, approved, sig/contributor-experience, sig/cluster-lifecycle, sig/architecture, sig/apps, size/XXL, sig/cloud-provider, cncf-cla: yes, lgtm, sig/node, sig/network, sig/docs, sig/instrumentation, sig/service-catalog, sig/scalability, sig/release, area/provider/azure, sig/windows, sig/cli, area/provider/openstack, sig/api-machinery, wg/policy, wg/component-standard, sig/usability, area/github-management, sig/k8s-infra

#4343 SIG Autoscaling Github Groups Cleanup
  config/kubernetes/org.yaml
  config/kubernetes/sig-autoscaling/teams.yaml
  config/restrictions.yaml
Labels: size/L, approved, cncf-cla: yes, lgtm, sig/autoscaling, area/github-management

#4352 Add members 2023-07-28
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-management

#4355 Add cloud-provider-equinix-metal teams
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, sig/cloud-provider, cncf-cla: yes, lgtm, area/github-management
