Repository kubernetes/org, pull requests merged in 2023-01, with the labels that each got.

#3913 Add GitHub teams for windows-service-proxy repo
  config/kubernetes-sigs/sig-windows/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/windows, area/github-management

#3914 Add songxiao-wang87 to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3899 Add myself to kubernetes (already in kubernetes-sigs)
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#3900 add mwielgus to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3908 update sig-release teams for 1.27 release
  config/kubernetes/sig-release/teams.yaml
Labels: size/L, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#3916 add nawazkh to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, needs-ok-to-test, approved, cncf-cla: yes, lgtm, area/github-management

#3532 add nilekhc and salaxander to secrets-store-csi-driver maintainers
  config/kubernetes-sigs/sig-auth/teams.yaml
Labels: size/XS, sig/auth, approved, cncf-cla: yes, lgtm, area/github-management

#3920 adding `jrsapi` to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3923 update github handle fromanirh -> ffromani
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3927 Updated CAPG groups with current maintainers
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/S, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#3933 Add members 2023-01-12
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-management

#3934 Add make target to add org members
  Makefile
  README.md
  hack/add-members.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, area/github-management

#3881 Update AWS enc provider admins and maintainers
  config/kubernetes-sigs/sig-aws/teams.yaml
Labels: size/XS, area/provider/aws, approved, sig/cloud-provider, cncf-cla: yes, lgtm, area/github-management

#3937 Add cap-addon-provider-helm-teams
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/S, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-repo, area/github-management

#3945 Add teams for sig-multicluster-site repo
  config/kubernetes-sigs/sig-multicluster/teams.yaml
Labels: sig/multicluster, size/S, approved, cncf-cla: yes, lgtm, area/github-repo, area/github-management

#3943 Revert "Remove qiujian16 from kubernetes-sigs org"
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#3954 add dprotaso to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3948 Add `haircommander` to `cri-tools-maintainers`
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3958 Add Fish-pro to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3944 Add Kubernetes 1.27 Enhancements Team members to the GitHub organizations
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3965 Add members 2023-01-18
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-management

#3967 Add torredil to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, needs-ok-to-test, approved, cncf-cla: yes, lgtm, area/github-management

#3942 Adding 1.27 enhancements team to appropriate groups
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: size/S, approved, sig/architecture, cncf-cla: yes, lgtm, sig/release, area/github-management

#3968 add fengshunli to kubernetes-csi, kubernetes-client
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3969 Add members 2023-01-19
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3979 sig-instrumentation: Add mrueg
  config/kubernetes/sig-instrumentation/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/instrumentation, area/github-management

#3980 Promote cici37 to kubernetes nightly org member
  config/kubernetes-nightly/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3986 Add members 2023-01-26
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#3988 Add saurav-agarwalla to kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, needs-ok-to-test, approved, cncf-cla: yes, lgtm, area/github-management

#3994 Add `rexagod` to sig-instrumentation
  config/kubernetes/sig-instrumentation/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/instrumentation, area/github-management

#3990 Add members to appropriate groups for being Release Manager Associates
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#3949 Add `harche` to SIG Node teams
  config/kubernetes/sig-node/teams.yaml
Labels: kind/bug, kind/feature, size/XS, approved, cncf-cla: yes, lgtm, sig/node, kind/design, area/github-management

#3947 Add `saschagrunert` to SIG Node teams
  config/kubernetes/sig-node/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/node, area/github-management
