Repository kubernetes/org, pull requests merged in 2024-01, with the labels that each got.

#4644 Add nrb to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#4645 Adding AravindhP as maintainter to sig-windows-tool repo
  config/kubernetes-sigs/sig-windows/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/windows, area/github-management

#4646 Updating sig-windows github groups
  config/kubernetes-sigs/sig-windows/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/windows, area/github-management

#4643 Add 1.30 Release Team Permissions
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M, area/github-management

#4647 sig-release: add team repo permissions for obscli
  config/kubernetes-sigs/sig-release/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4651 add nnmin-aws to aws-iam-authenticator-maintainers
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Labels: size/XS, approved, sig/cloud-provider, cncf-cla: yes, lgtm, area/github-management

#4656 Add members 2024-01-04-eve
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4659 Add Members 2024-01-06
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4661 Add members 2024-01-08
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4655 Add members 2024-01-04
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4662 Add Members 2024-01-08-noon
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4664 Add Members 2024-01-08-eve
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4665 Add mfahlandt to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4660 [1.30] Add Leads to Milestone Maintainers
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: size/S, approved, sig/architecture, cncf-cla: yes, lgtm, sig/release, area/github-management

#4667 config: add teams for hydrophone under k-sigs/sig-testing
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/restrictions.yaml
Labels: sig/testing, size/S, approved, cncf-cla: yes, lgtm, area/github-management

#4670 Add members 2024-01-11
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4672 sig network: add teams for node-ipam-controller repo
  config/kubernetes-sigs/sig-network/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#4679 Add members 2024-01-15
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4671 Add members 2024-01-12
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4684 Add members 2024-01-16
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4693 Add members 2024-01-18
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4695 Add members 2024-01-19
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4677 add 1.30 Enhancements Team
  config/kubernetes/sig-release/teams.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4690 Add 1.30 Docs Shadows to GitHub teams
  config/kubernetes/sig-docs/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: size/S, approved, kind/documentation, cncf-cla: yes, lgtm, sig/docs, sig/release, area/github-management

#4692 Add 1.30 Comms shadows to github teams
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm, sig/release, area/github-management

#4701 Add members 2024-01-21
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4650 remove kbhawkey from sig docs leads
  OWNERS_ALIASES
  config/kubernetes-sigs/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#4700 Add members 2024-01-20
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4702 chore: update sig-network team.yaml for blixt project admins
  config/kubernetes-sigs/sig-network/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#4704 Add teams for knftables repo
  config/kubernetes-sigs/sig-network/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/network, area/github-repo, area/github-management

#4703 Add Release Notes Shadows 1.30
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4707 Add jpbetz to milestone maintainer team
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4291 korg: add audit command
  cmd/korg/audit.go
  cmd/korg/korg.go
  cmd/korg/utils.go
  docs/sample-exceptions.csv
  go.mod
  go.sum
Labels: approved, size/XL, cncf-cla: yes, lgtm, area/github-management

#4713 Minor: fix typo in GitHub Handle (Priyankasaggu11929)
  Makefile
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4709 Remove tnozicka from sig-apps teams
  config/kubernetes/sig-apps/teams.yaml
Labels: size/XS, approved, sig/apps, cncf-cla: yes, lgtm, area/github-management

#4712 Add members 2024-01-23
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4720 Add jasonbraganza to kubernetes-client, kubernetes-csi
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4698 Add jpbetz to PRR reviewer team
  config/kubernetes/sig-architecture/teams.yaml
Labels: size/XS, approved, sig/architecture, cncf-cla: yes, lgtm, area/github-management

#4716 Add members 2024-01-24
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4718 Add members 2024-01-25
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4719 NMC: promote jasonbraganza as approver for active orgs
  config/kubernetes-client/OWNERS
  config/kubernetes-csi/OWNERS
  config/kubernetes-sigs/OWNERS
  config/kubernetes/OWNERS
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-management

#4498 Add etcd-io org
  config/etcd-io/OWNERS
  config/etcd-io/org.yaml
  config/restrictions.yaml
Labels: size/L, approved, cncf-cla: yes, lgtm, area/github-management, sig/etcd

#4725 Add fabriziopandini to CAPV GitHub admins and maintainers
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#4727 Sync CAPZ owners with Azure provider project
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/S, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#4728 Add uablrek to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4729 add adityabhatia to kubernetes-sigs, kubernetes
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4723 update kustomize owners
  config/kubernetes-sigs/sig-cli/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/cli, tide/merge-method-squash, area/github-management
