Repository kubernetes/org, pull requests merged in 2024-06, with the labels that each got.

#4998 Add 1.31 release branch manager permissions
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4999 update cloud-provider-gcp admins and remove inactive members
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4993 Kubespray/maintainers: add VannTeen
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#5000 Add richabanker as PRR shadow
  config/kubernetes/sig-architecture/teams.yaml
Labels: size/XS, approved, sig/architecture, cncf-cla: yes, lgtm, area/github-management

#5002 Add benluddy to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5005 Add members 2024-06-07
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5006 Add bells17 to sig-docs-ja-owners team
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#4846 Add kirkonru to sig-docs-ru
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#5007 Add EmilienM to CAPO admins
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#5012 Add members 2024-06-11
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5010 sig-arch: Add verify-conformance teams
  config/kubernetes-sigs/sig-architecture/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, sig/architecture, cncf-cla: yes, lgtm, area/github-repo, area/github-management

#5014 Add members 2024-06-12
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5001 Add ybettan to KMM admin teams
  config/kubernetes-sigs/sig-node/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/node, area/github-management

#5018 Add members 2024-06-14
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5015 Add hime as maintainer to pdcsi and filestorecsi github repos
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#4929 kubernetes-sigs: move sig-storage gh teams to respective teams.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-storage/teams.yaml
  config/restrictions.yaml
Labels: size/L, sig/storage, approved, kind/cleanup, cncf-cla: yes, lgtm, area/github-management

#5021 Ingress NGINX: Promote Gacko to admin.
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5024 Add members 2024-06-15
  config/etcd-io/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5025 Add members 2024-06-17
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#5026 add ericsmalling to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4995 sig-release: Add subproject leads as reviewers/approvers
  OWNERS_ALIASES
  config/kubernetes-nightly/sig-release/OWNERS
  config/kubernetes-sigs/sig-release/OWNERS
  config/kubernetes/sig-release/OWNERS
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#5030 Add members 2024-06-19
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5027 Add members 2024-06-17
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5033 Add members 2024-06-21
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5035 Add dipesh-rawat to sig-docs-hi-owners and sig-docs-hi-reviews
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#5029 chore: specify go patch version
  go.mod
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5037 add mszadkow to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5003 infra/testing teams cleanup
  config/kubernetes-sigs/sig-k8s-infra/teams.yaml
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-k8s-infra/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: sig/testing, size/S, approved, sig/architecture, cncf-cla: yes, lgtm, sig/release, area/github-management, sig/k8s-infra
