Repository kubernetes/org, pull requests merged in 2024-02, with the labels that each got.

#4730 sig-cluster-lifecycle/cluster-api: add chrischdi to maintainers
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#4735 Add gjtempleton to Milestone Maintainer team
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4738 Add members 2024-02-07
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4739 Add members 2024-02-07-eve
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4717 commenting in daniel chan now that his org request is approved.
  config/kubernetes/sig-docs/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, sig/release, area/github-management

#4742 update sig-network-leads team
  config/kubernetes/sig-network/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/network, area/github-management

#4743 Add members 2024-02-08
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4746 Add members 2024-02-09
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4747 Add alculquicondor to milestone-maintainers
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4749 add mneverov to kubernetes org
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4750 Remove funding repo
  config/kubernetes/org.yaml
  config/restrictions.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4752 Add etcd-io org to repo templates
  .github/ISSUE_TEMPLATE/membership.yml
  .github/ISSUE_TEMPLATE/repo-create.yml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4753 Add members 2024-02-13
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4755 Added team for etcd-io/auger
  config/etcd-io/org.yaml
  config/restrictions.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, area/github-management

#4764 Update team members for CAAPH
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#4766 Add jongwooo to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4761 add nasa9084 to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4765 Update korg tool to recognise etcd-io org
  cmd/korg/korg.go
  hack/default-branches-report.sh
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4767 Add erikgrinaker to etcd-io members
  config/etcd-io/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4758 Remove inactive members - 2024
  cmd/korg/korg.go
  cmd/korg/remove.go
  cmd/korg/utils.go
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/provider-ibmcloud/teams.yaml
  config/kubernetes-sigs/provider-vmware/teams.yaml
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
  config/kubernetes-sigs/sig-apps/teams.yaml
  config/kubernetes-sigs/sig-architecture/teams.yaml
  config/kubernetes-sigs/sig-auth/teams.yaml
  config/kubernetes-sigs/sig-aws/teams.yaml
  config/kubernetes-sigs/sig-cli/teams.yaml
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
  config/kubernetes-sigs/sig-multicluster/teams.yaml
  config/kubernetes-sigs/sig-network/teams.yaml
  config/kubernetes-sigs/sig-release/teams.yaml
  config/kubernetes-sigs/sig-storage/teams.yaml
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/kubernetes-sigs/sig-windows/teams.yaml
  config/kubernetes-sigs/wg-policy/teams.yaml
  config/kubernetes/org.yaml
  config/kubernetes/provider-azure/teams.yaml
  config/kubernetes/provider-gcp/OWNERS
  config/kubernetes/provider-gcp/teams.yaml
  config/kubernetes/provider-openstack/teams.yaml
  config/kubernetes/sig-api-machinery/teams.yaml
  config/kubernetes/sig-apps/teams.yaml
  config/kubernetes/sig-auth/teams.yaml
  config/kubernetes/sig-cloud-provider/teams.yaml
  config/kubernetes/sig-cluster-lifecycle/teams.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-docs/teams.yaml
  config/kubernetes/sig-instrumentation/teams.yaml
  config/kubernetes/sig-multicluster/teams.yaml
  config/kubernetes/sig-network/teams.yaml
  config/kubernetes/sig-node/teams.yaml
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-scalability/teams.yaml
  config/kubernetes/sig-storage/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
  config/kubernetes/ug-big-data/OWNERS
  config/kubernetes/ug-big-data/teams.yaml
Labels: sig/auth, area/provider/aws, sig/multicluster, sig/testing, area/provider/vmware, area/provider/gcp, sig/storage, area/provider/ibmcloud, approved, sig/contributor-experience, sig/cluster-lifecycle, sig/architecture, sig/apps, size/XXL, sig/cloud-provider, cncf-cla: yes, lgtm, sig/node, ug/big-data, sig/network, sig/docs, sig/instrumentation, sig/scalability, sig/release, area/provider/azure, sig/windows, sig/cli, area/provider/openstack, sig/api-machinery, wg/policy, area/github-membership, area/github-management

#4769 Add RT lead shadows to teams
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#4721 update e2e-framework github team to reflect the actual members
  config/kubernetes-sigs/sig-testing/teams.yaml
Labels: size/XS, sig/testing, approved, cncf-cla: yes, lgtm, area/github-management

#4420 Add pwschuurman as maintainer to pdcsi and filestorecsi github repos
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4771 Grant admin permisssion for auger to maintainers-auger team
  config/etcd-io/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4772 Add members 19 feb 2024
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4734 config: setup apisnoop repo
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-architecture/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, sig/architecture, cncf-cla: yes, lgtm, area/github-management

#4773 Add members 2024-02-19
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4775 Update cluster-api-operator-admins
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#4776 add tnqn to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4778 Add torredil to kubernetes-csi org
  config/kubernetes-csi/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4780 sig apps: add team repo permissions for lws repo
  config/kubernetes-sigs/sig-apps/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, sig/apps, cncf-cla: yes, lgtm, area/github-management

#4782 Add amacaskill as maintainer to filestorecsi github repos
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4785 Add members 2024-02-25
  config/kubernetes-client/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4786 Add new teams for kubernetes-sigs/testgrid
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/restrictions.yaml
Labels: sig/testing, size/S, approved, cncf-cla: yes, lgtm, area/github-management

#4787 Add new teams for kubernetes-sigs/referencegrant-poc
  config/kubernetes-sigs/sig-auth/teams.yaml
  config/restrictions.yaml
Labels: sig/auth, size/S, approved, cncf-cla: yes, lgtm, area/github-management

#4788 Add members 2024-02-27
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4792 Add members 2024-02-28
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4796 Rename AhmedGrati -> TessaIO
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
  config/kubernetes/sig-apps/teams.yaml
Labels: size/XS, approved, sig/apps, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#4798 Add members 2024-02-29
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#4789 Promote drew-viles to maintainer of image-builder
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management
