Repository kubernetes/org, pull requests merged in 2024-09, with the labels that each got.

#5124 Add dipesh-rawat to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5128 Add mimowo and remove ahg-g from Kueue admins
  config/kubernetes-sigs/sig-scheduling/teams.yaml
Labels: size/XS, sig/scheduling, approved, cncf-cla: yes, lgtm, area/github-management

#5125 Add 1.32 release team permissions
  config/kubernetes/sig-release/teams.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M, area/github-management

#5130 Add org members – Sept 5, 2024
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5135 Add members 2024-09-07
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5137 Elevate etcd team permissions for release window
  config/etcd-io/sig-etcd/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management, sig/etcd

#5096 Add `rexagod` to `milestone-maintainers`
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#5139 Add kannon92 to some sig-node orgs
  config/kubernetes/sig-node/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/node, area/github-management

#5141 Add mcbenjemaa as cluster-api-ipam-provider-in-cluster maintainer
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Labels: size/XS, approved, sig/cluster-lifecycle, cncf-cla: yes, lgtm, area/github-management

#5142 Revert "Elevate etcd team permissions for release window"
  config/etcd-io/sig-etcd/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management, sig/etcd

#5144 Add members 2024-09-12
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5151 add kfswain to Kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5153 Add kfswain to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5156 Add members 2024-09-14
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5159 Add enhancements team for 1.32 to appropriate groups
  config/kubernetes/sig-architecture/teams.yaml
  config/kubernetes/sig-release/teams.yaml
Labels: size/S, approved, sig/architecture, cncf-cla: yes, lgtm, sig/release, area/github-management

#5164 Add members 2024-09-17
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5167 Add members 2024-09-18
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5145 Added Comms shadows for 1.32
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#5161 Adding Release Signal Shadows
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#5173 Add members 2024-09-19
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5174 Add members 2024-09-20
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5147 sig-network: add gh teams for gwctl repo
  config/kubernetes-sigs/sig-network/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm, sig/network, area/github-repo, area/github-management

#5163 Add 1.32 release docs subteam permissions
  config/kubernetes/sig-release/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/release, area/github-management

#5175 Add mimowo to the sig-apps team
  config/kubernetes/sig-apps/teams.yaml
Labels: size/XS, approved, sig/apps, cncf-cla: yes, lgtm, area/github-management

#5183 sig-cluster-lifecycle: add karpenter-provider-cluster-api github teams
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
  config/restrictions.yaml
Labels: size/S, approved, cncf-cla: yes, lgtm

#5184 Add members 2024-09-26
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5188 Add members 2024-09-28
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management
