Repository kubernetes/org, pull requests merged in 2025-07, with the labels that each got.

#5689 add alaypatel07 to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5655 Adding Andygol as reviewer/approver for Ukrainian content
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management

#5692 add taylorwaggoner to kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5697 Add members 2025-07-11
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5698 Rename members 2025-07-11 (m00nf1sh -> M00nF1sh)
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, sig/cloud-provider, cncf-cla: yes, lgtm, area/github-management

#5691 Update admin / maintainer groups for controller-runtime & controller-tools
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/api-machinery, area/github-management

#5702 Add ryanzhang-oss to kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#5709 Add members 2025 07 18
  config/kubernetes-sigs/org.yaml
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-membership, area/github-management

#5715 add hwdef to etcd-io
  config/etcd-io/org.yaml
  config/etcd-io/sig-etcd/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management, sig/etcd

#5719 Fix documentation in hack/remove-members.sh
  hack/remove-members.sh
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5720 Add stlaz to kubernetes-sigs org
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5718 Clean up inactive members - June 2025
  config/etcd-io/org.yaml
  config/etcd-io/sig-etcd/teams.yaml
  config/kubernetes-client/org.yaml
  config/kubernetes-csi/org.yaml
  config/kubernetes-sigs/org.yaml
  config/kubernetes-sigs/provider-vmware/teams.yaml
  config/kubernetes-sigs/sig-api-machinery/teams.yaml
  config/kubernetes-sigs/sig-architecture/teams.yaml
  config/kubernetes-sigs/sig-aws/teams.yaml
  config/kubernetes-sigs/sig-cli/teams.yaml
  config/kubernetes-sigs/sig-cloud-provider/teams.yaml
  config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
  config/kubernetes-sigs/sig-contributor-experience/teams.yaml
  config/kubernetes-sigs/sig-instrumentation/teams.yaml
  config/kubernetes-sigs/sig-multicluster/teams.yaml
  config/kubernetes-sigs/sig-network/teams.yaml
  config/kubernetes-sigs/sig-node/teams.yaml
  config/kubernetes-sigs/sig-scheduling/teams.yaml
  config/kubernetes-sigs/sig-storage/teams.yaml
  config/kubernetes-sigs/sig-testing/teams.yaml
  config/kubernetes-sigs/wg-naming/teams.yaml
  config/kubernetes/org.yaml
  config/kubernetes/provider-azure/teams.yaml
  config/kubernetes/provider-ibmcloud/teams.yaml
  config/kubernetes/provider-openstack/teams.yaml
  config/kubernetes/sig-api-machinery/teams.yaml
  config/kubernetes/sig-apps/teams.yaml
  config/kubernetes/sig-cluster-lifecycle/teams.yaml
  config/kubernetes/sig-contributor-experience/teams.yaml
  config/kubernetes/sig-docs/teams.yaml
  config/kubernetes/sig-instrumentation/teams.yaml
  config/kubernetes/sig-k8s-infra/teams.yaml
  config/kubernetes/sig-multicluster/teams.yaml
  config/kubernetes/sig-network/teams.yaml
  config/kubernetes/sig-release/teams.yaml
  config/kubernetes/sig-storage/teams.yaml
  config/kubernetes/sig-testing/teams.yaml
  config/kubernetes/wg-naming/teams.yaml
  config/kubernetes/wg-structured-logging/teams.yaml
  config/restrictions.yaml
Labels: area/provider/aws, sig/multicluster, sig/testing, area/provider/vmware, sig/storage, area/provider/ibmcloud, sig/scheduling, approved, sig/contributor-experience, sig/cluster-lifecycle, sig/architecture, sig/apps, size/XL, sig/cloud-provider, cncf-cla: yes, lgtm, sig/node, sig/network, sig/docs, sig/instrumentation, sig/release, area/provider/azure, sig/cli, area/provider/openstack, sig/api-machinery, wg/naming, area/github-management, sig/k8s-infra, sig/etcd

#5732 etcd: Update release-etcd team for release window
  config/etcd-io/sig-etcd/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management, sig/etcd

#5738 etcd: Restore release-etcd team members
  config/etcd-io/sig-etcd/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management, sig/etcd

#5744 add kflynn to kubernetes
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, ok-to-test, area/github-management

#5730 Update maintainer list for ingress-gce
  config/kubernetes/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5746 add rushmash91 to kubernetes-sigs
  config/kubernetes-sigs/org.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/github-management

#5716 Add graz-dev as blog owner
  config/kubernetes/sig-docs/teams.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm, sig/docs, area/github-management
